---
server:
  port: 9090
  disable_lanid: true
  allow_registration: false
  allow_setup: true
  servlet:
    context-path: "/"
grails:
  profile: web
  codegen:
    defaultPackage: g6portal
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: "@info.app.name@"
    version: "@info.app.version@"
    grailsVersion: "@info.app.grailsVersion@"
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - "*.gsp"
        - "**/*.gsp"
        - "*.gson"
        - "**/*.gson"
        - "logback.groovy"
        - "*.properties"
environments:
  development:
    google:
      oauth:
        clientId: "client-id"
        clientSecret: "client-secret"
        callbackUrl: "callback-url"
    management:
      endpoints:
        enabled-by-default: true
        web:
          base-path: "/actuator"
          exposure:
            include: "*"
  production:
    google:
      oauth:
        clientId: "client-id"
        clientSecret: "client-secret"
        callbackUrl: "callback-url"
    management:
      endpoints:
        enabled-by-default: false

---
grails:
  mail:
    host: 127.0.0.1
    port: 8025
    username: "mailusername"
    password: "mailpassword"
    disabled: false
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: "*/*"
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
    upload:
      maxFileSize: -1
      maxRequestSize: -1
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
---
hibernate:
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: true
    region:
      factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
dataSource:
  pooled: true
  jmxExport: true
  # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  driverClassName: org.h2.Driver
  # Disable both driverClassName above to use postgres
  username: sa
  password:

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:h2:./g6db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;MODE=PostgreSQL
      # url: jdbc:postgresql://localhost:5432/g6portal?stringtype=unspecified
      # url: jdbc:sqlserver://localhost:1433;databaseName=g6portal;encrypt=true;trustServerCertificate=true;
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:./g6db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;MODE=PostgreSQL
      # url: jdbc:postgresql://localhost:5432/g6portal?stringtype=unspecified
      # url: jdbc:sqlserver://localhost:1433;databaseName=g6portal;encrypt=true;trustServerCertificate=true;
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
  production:
    dataSource:
      dbCreate: update
      url: jdbc:h2:./g6db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;MODE=PostgreSQL
      # url: jdbc:postgresql://localhost:5432/g6portal?stringtype=unspecified
      # url: jdbc:sqlserver://localhost:1433;databaseName=g6portal;encrypt=true;trustServerCertificate=true;
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
